"""empty message

Revision ID: ff2a93cab278
Revises: 
Create Date: 2024-01-12 10:09:15.095802

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ff2a93cab278'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('emaill_UNIQUE', table_name='usuario')
    op.drop_table('usuario')
    op.drop_index('fk_idfarefas_idx', table_name='usuario_tarefas')
    op.drop_index('fk_idusuario_idx', table_name='usuario_tarefas')
    op.drop_table('usuario_tarefas')
    op.drop_index('fk_idprovas_idx', table_name='usuario_provas')
    op.drop_index('fk_idusuario_idx', table_name='usuario_provas')
    op.drop_table('usuario_provas')
    op.drop_index('fk_idmaterias_idx', table_name='tarefas')
    op.drop_table('tarefas')
    op.drop_index('fk_idmaterias_idx', table_name='usuario_materias')
    op.drop_index('fk_idusuario_idx', table_name='usuario_materias')
    op.drop_table('usuario_materias')
    op.drop_index('fk_idmaterias_idx', table_name='provas')
    op.drop_table('provas')
    op.drop_table('materias')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('materias',
    sa.Column('idmaterias', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', mysql.VARCHAR(length=45), nullable=False),
    sa.Column('data', sa.DATE(), nullable=False),
    sa.Column('hora', mysql.TIME(), nullable=False),
    sa.Column('professor', mysql.VARCHAR(length=45), nullable=False),
    sa.PrimaryKeyConstraint('idmaterias'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('provas',
    sa.Column('idprovas', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('dia', sa.DATE(), nullable=False),
    sa.Column('hora', mysql.TIME(), nullable=False),
    sa.Column('valor', mysql.DECIMAL(precision=4, scale=2), nullable=False),
    sa.Column('idmaterias', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['idmaterias'], ['materias.idmaterias'], name='fk_idmaterias_nova'),
    sa.PrimaryKeyConstraint('idprovas'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('fk_idmaterias_idx', 'provas', ['idmaterias'], unique=False)
    op.create_table('usuario_materias',
    sa.Column('idusuario_materia', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('idusuario', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('idmaterias', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['idmaterias'], ['materias.idmaterias'], name='fk_idmaterias'),
    sa.ForeignKeyConstraint(['idusuario'], ['usuario.idusuario'], name='fk_idusuario'),
    sa.PrimaryKeyConstraint('idusuario_materia'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('fk_idusuario_idx', 'usuario_materias', ['idusuario'], unique=False)
    op.create_index('fk_idmaterias_idx', 'usuario_materias', ['idmaterias'], unique=False)
    op.create_table('tarefas',
    sa.Column('idtarefas', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('valor', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('dia', sa.DATE(), nullable=False),
    sa.Column('hora', mysql.TIME(), nullable=False),
    sa.Column('idmaterias', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('desc', mysql.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['idmaterias'], ['materias.idmaterias'], name='fk_idmaterias_nova1'),
    sa.PrimaryKeyConstraint('idtarefas'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('fk_idmaterias_idx', 'tarefas', ['idmaterias'], unique=False)
    op.create_table('usuario_provas',
    sa.Column('idusuario_provas', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('idusuario', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('idprovas', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['idprovas'], ['provas.idprovas'], name='fk_idprovas_usuario_provas'),
    sa.ForeignKeyConstraint(['idusuario'], ['usuario.idusuario'], name='fk_idusuario_usuario_provas'),
    sa.PrimaryKeyConstraint('idusuario_provas'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('fk_idusuario_idx', 'usuario_provas', ['idusuario'], unique=False)
    op.create_index('fk_idprovas_idx', 'usuario_provas', ['idprovas'], unique=False)
    op.create_table('usuario_tarefas',
    sa.Column('idusuario_tarefa', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('idusuario', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('idtarefas', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['idtarefas'], ['tarefas.idtarefas'], name='fk_idfarefas_usuario_tarefas'),
    sa.ForeignKeyConstraint(['idusuario'], ['usuario.idusuario'], name='fk_idusuario_usuario_tarefas'),
    sa.PrimaryKeyConstraint('idusuario_tarefa'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('fk_idusuario_idx', 'usuario_tarefas', ['idusuario'], unique=False)
    op.create_index('fk_idfarefas_idx', 'usuario_tarefas', ['idtarefas'], unique=False)
    op.create_table('usuario',
    sa.Column('idusuario', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('emaill', mysql.VARCHAR(length=45), nullable=False),
    sa.Column('nome', mysql.VARCHAR(length=45), nullable=False),
    sa.Column('senha', mysql.VARCHAR(length=45), nullable=False),
    sa.PrimaryKeyConstraint('idusuario'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('emaill_UNIQUE', 'usuario', ['emaill'], unique=True)
    # ### end Alembic commands ###
